chore(peerDepsReact): Raised react ver in peer deps
Groww/webster pull request #112
Opened 2022-09-16 05:48 UTC by abhishekjhagroww

## What does this PR do?

Raised react version to ^17.0.0 in all webster projects.

## What packages have been affected by this PR?
all packages

## Types of changes

version bump changes

What types of changes does your code introduce to this project?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in any of the packages?

Peer deps react from 16.2.1 to ^17.0.0

## Checklist before merging

_Put an `x` in the boxes that apply_

- [ ] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

2022-09-19 17:45 UTC, growwrishabh requested changes
Change it to ^16.12.0 || ^17.0.0 everywhere

2022-09-20 14:08 UTC, growwrishabh approved these changes

2022-10-06 12:15 UTC, rishavthakurgroww approved these changes

2022-12-28 08:03 UTC, harshitpruthi94 approved these changes

2022-12-28 09:13 UTC, rishabhtripathigroww approved these changes

2022-12-28 09:27 UTC, bhaveshgoyal155 approved these changes

2022-12-28 10:47 UTC, merged