Web monitoring service
Groww/webster pull request #189
Opened 2023-03-22 14:43 UTC by shubhamgavali1998

## What does this PR do?

# Monitoring package

- [ ] Bugfix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in any of the packages?

## Checklist before merging

_Put an `x` in the boxes that apply_

- [ ] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

2023-03-27 06:27 UTC, tusharsehwagg requested changes

2023-03-27 06:27 UTC, tusharsehwagg commented on packages/monitoring/package.json
> +  "main": "src/index.ts",
serve it from dist folder and add module and types too. Take reference from ella.

2023-03-27 06:27 UTC, tusharsehwagg commented on packages/monitoring/package.json
> +    "@groww-tech/ella": "0.2.4",
ella is a dev dependency?

2023-03-27 06:27 UTC, tusharsehwagg commented on packages/monitoring/src/index.ts
> +import client from 'prom-client';
can name it promClient or more better prometheusClient

2023-03-27 06:27 UTC, tusharsehwagg commented on packages/monitoring/src/index.ts
> +export function initPrometheus(PROMETHEUS_PORT: number, routeToExpose: string) {
as per the example provided above in readme, second param should be optional either or should update in readme too.

2023-03-27 06:44 UTC, shubhamgavali1998 commented on packages/monitoring/package.json
> +    "@groww-tech/ella": "0.2.4",
removed ella, it was not getting used

2023-03-28 08:06 UTC, abhishekjhagroww approved these changes

2023-03-28 08:08 UTC, tusharsehwagg approved these changes

2023-03-28 08:08 UTC, merged