padding fixes in components
Groww/webster pull request #376
Opened 2023-11-30 12:17 UTC by aditiSoniWeb

## What does this PR do?

Padding Fixes in Components such as in RadioButton, CheckBox
LoadingState in Button
Border in Pill

## What packages have been affected by this PR?

## Types of changes

What types of changes does your code introduce to this project?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in any of the packages?

## Checklist before merging

_Put an `x` in the boxes that apply_

- [ ] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

2023-11-30 12:22 UTC, AkshayNaikGroww requested changes

2023-11-30 12:24 UTC, shubhamgavali1998 commented on packages/ui-toolkit/src/components/atoms/RadioButton/radioButton.css
> +  justify-content: space-between;
same as above comment

2023-11-30 12:47 UTC, shubhamgavali1998 approved these changes

2023-12-01 05:22 UTC, AkshayNaikGroww approved these changes

2023-12-01 05:22 UTC, merged